Добавляет наставника
htmlacademy-adaptive/2166819-cat-energy-27 pull request #1
Opened 2022-11-23 10:48 UTC by Alexandraduga

2022-11-23 11:17 UTC, pavel-nyukalo requested changes

2022-11-23 11:17 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Давай добавим и мне ссылку, по аналогии с твоей `[Текст ссылки](сама ссылка)`

2022-11-23 13:53 UTC, Alexandraduga commented on Readme.md
> +* Наставник: `Павел Нюкало`.
во я дурак....

2022-11-24 05:57 UTC, pavel-nyukalo approved these changes

2022-11-24 05:57 UTC, merged